/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'

const IndexLazyRouteImport = createFileRoute('/')()
const AuthIndexLazyRouteImport = createFileRoute('/auth/')()
const AppIndexLazyRouteImport = createFileRoute('/app/')()
const AppIntegrationsLazyRouteImport = createFileRoute('/app/integrations')()
const AppOrdersIndexLazyRouteImport = createFileRoute('/app/orders/')()
const AppOrdersIdLazyRouteImport = createFileRoute('/app/orders/$id')()

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AuthIndexLazyRoute = AuthIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))
const AppIndexLazyRoute = AppIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() => import('./routes/app/index.lazy').then((d) => d.Route))
const AppIntegrationsLazyRoute = AppIntegrationsLazyRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() =>
  import('./routes/app/integrations.lazy').then((d) => d.Route),
)
const AppOrdersIndexLazyRoute = AppOrdersIndexLazyRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() =>
  import('./routes/app/orders.index.lazy').then((d) => d.Route),
)
const AppOrdersIdLazyRoute = AppOrdersIdLazyRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() =>
  import('./routes/app/orders.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/integrations': typeof AppIntegrationsLazyRoute
  '/app/': typeof AppIndexLazyRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/app/orders/$id': typeof AppOrdersIdLazyRoute
  '/app/orders/': typeof AppOrdersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/app/integrations': typeof AppIntegrationsLazyRoute
  '/app': typeof AppIndexLazyRoute
  '/auth': typeof AuthIndexLazyRoute
  '/app/orders/$id': typeof AppOrdersIdLazyRoute
  '/app/orders': typeof AppOrdersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/integrations': typeof AppIntegrationsLazyRoute
  '/app/': typeof AppIndexLazyRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/app/orders/$id': typeof AppOrdersIdLazyRoute
  '/app/orders/': typeof AppOrdersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/integrations'
    | '/app/'
    | '/auth/'
    | '/app/orders/$id'
    | '/app/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/integrations'
    | '/app'
    | '/auth'
    | '/app/orders/$id'
    | '/app/orders'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/integrations'
    | '/app/'
    | '/auth/'
    | '/app/orders/$id'
    | '/app/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexLazyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsLazyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexLazyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdLazyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIntegrationsLazyRoute: typeof AppIntegrationsLazyRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppOrdersIdLazyRoute: typeof AppOrdersIdLazyRoute
  AppOrdersIndexLazyRoute: typeof AppOrdersIndexLazyRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIntegrationsLazyRoute: AppIntegrationsLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppOrdersIdLazyRoute: AppOrdersIdLazyRoute,
  AppOrdersIndexLazyRoute: AppOrdersIndexLazyRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
